# Deploy to these servers.
servers:
  web:
    - 172.105.202.16
  cron:
    hosts:
      - 172.105.202.16
    cmd:
      bash -c "(env && cat config/crontab) | crontab - && cron -f"
    options:
      user: root
  job:
    hosts:
      - 172.105.202.16
    cmd: bin/jobs

registry:
  # Specify the registry server, if you're not using Docker Hub
  # server: registry.digitalocean.com / ghcr.io / ...
  username: brincmafai

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_PASSWORD
